name: Cypress Tests
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: self-hosted
#     ...specific container can be used:
#     container: cypress/browsers:node12.13.0-chrome78-ff70
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          command: npm run cy:run
#         ...or
#          browser: chrome
#          spec: cypress/e2e/real-world-app/*
#        ...env variables can be added as well
#        env:
#          CYPRESS_host: localhost
#          CYPRESS_port: 3000
